### ISSUE TITLE
collaboration desired

### ISSUE THREAD

**Issue by ORESoftware** [nemisj/yield-yield#2]
hey there!

I saw your examples with Mocha - I am developing a test framework 
https://github.com/ORESoftware/suman

have you heard of AVA? well Suman is to Mocha, as AVA is to Tape.

I like your pattern with Mocha, and am still trying to figure out how to best incorporate generators into Suman. I frankly don't really understand generators very well yet.

Let me know if you are interested in helping out, thanks!

**Comment by ORESoftware** [comment]
your article is really good

but actually this article makes even more sense to me:

https://www.promisejs.org/generators/

have you seen that one?

**Comment by nemisj** [comment]
@ORESoftware, hi, sorry , looks like my email notifications are off in github. will fix them.
How can i help you?
