### ISSUE TITLE
yield yield and Promise.all

### ISSUE THREAD

**Issue by TuningGuide** [nemisj/yield-yield#3]
Hi, I'm having trouble with yield yield and Promise.all. I'm having something like

	o_o(...
		let promises = links.map(function* (link) {
			let response = yield request({uri: link, headers: headers}, yield);
			// do something with result and return new Promise
		});

		let all = yield Promise.all(promises);
	)();

But it directly steps to Promise.all instead of running through the links first.
What I want to accomplish is:
for every link do request and process body as soon it's available
wait until all body's are processed.

Regards

**Comment by nemisj** [comment]
Currently, you can't use `map` the way you've implemented it. Since map is outside `yield-yield` generator. For your solution you have to use native loops and you don't need `Promise.all` for that.

```javascript
o_o(...
    const all = [];
    for (var i = 0; i < links.length; i++) {
        const link = links[i];
        all.push(yield request({uri: link, headers: headers}, yield)
    }

    // all is filled with results
)();
```

**Comment by TuningGuide** [comment]
If I'm right the problem with this approach is that it is sequential.

**Comment by nemisj** [comment]
You're right. it's sequential solution. But that's the whole point of yield yield. Do you need parallel?

**Comment by nemisj** [comment]
FYI: I've implemented parallel functionality in yield-yield https://github.com/nemisj/yield-yield/blob/master/docs/API.md#import--qcollect-qrun--from-yield-yield

**Comment by TuningGuide** [comment]
Great news. Thank you very much
