### ISSUE TITLE
Change let to var

### ISSUE THREAD

**Issue by jshuaf** [nemisj/yield-yield#7]
In index.js, line 405, you have:
`let message = 'Arguments mismatch, too much arguments passed. Wanted ' . . .`

You need to change the let to a var... for compatibility.

**Comment by bjb568** [comment]
Compatibility with what? There aren't many environments that support generators but not `let`.

**Comment by jshuaf** [comment]
It's not a problem anymore... but I had needed to use UglifyJS to minify the package's source.

**Comment by jshuaf** [comment]
Actually... this would still be helpful.

**Comment by nemisj** [comment]
good point @jshuaf , will do that. was in vacation

**Comment by nemisj** [comment]
https://github.com/nemisj/yield-yield/releases/tag/v1.3.1
